export const photos = [
    require("./assets/1.jpg"),
    require("./assets/2.jpg"),
    require("./assets/4.jpg"),
    require("./assets/5.jpg"),
    require("./assets/7.jpg"),
    require("./assets/8.jpg"),
    require("./assets/11.jpg"),
    require("./assets/10.jpg"),
    require("./assets/3.jpg"),
    require("./assets/12.jpg"),
    require("./assets/13.jpg"),
    require("./assets/39.jpeg"),
    require("./assets/24.jpg"),
    require("./assets/14.jpg"),
    require("./assets/9.jpg"),
    require("./assets/40.jpeg"),
    require("./assets/18.jpg"),
    require("./assets/29.jpeg"),
    require("./assets/20.jpg"),
    require("./assets/23.jpg"),
    require("./assets/6.jpg"),
    require("./assets/41.jpeg"),
    require("./assets/17.jpg"),
    require("./assets/30.jpeg"),
    require("./assets/15.jpg"),
    require("./assets/19.jpg"),
    require("./assets/26.jpeg"),
    require("./assets/21.jpg"),
    require("./assets/22.jpg"),
    require("./assets/37.jpeg"),
    require("./assets/31.jpg"),
    require("./assets/42.jpeg"),
    require("./assets/28.jpeg"),
    require("./assets/32.jpg"),
    require("./assets/72.jpeg"),
    require("./assets/25.jpg"),
    require("./assets/38.jpg"),
    require("./assets/27.jpeg"),
    require("./assets/33.jpg"),
    require("./assets/42.jpg"),
    require("./assets/school_1.jpg"),
    require("./assets/47.jpg"),
    require("./assets/49.jpg"),
    require("./assets/53.jpg"),
    require("./assets/34.jpeg"),
    require("./assets/57.jpg"),
    require("./assets/35.jpeg"),
    require("./assets/64.jpg"),
    require("./assets/37.jpeg"),
    require("./assets/70.jpg"),
    require("./assets/36.jpeg"),



    
];
